name: togeojson
version: master
summary: convert KML and GPX to GeoJSON, without the fuss
description: |
  This converts KML & GPX to GeoJSON, in a browser or with Node.js

grade: stable
confinement: strict

apps:
  togeojson:
    command: togeojson
    plugs: [home]

parts:
  togeojson:
    source: .
    plugin: nodejs
